name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/0.6.2/install.sh | sh
          # Add uv's bin directories to PATH
          echo "PATH=/root/.uv/bin:/root/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        run: uv sync --active
      
      - name: Run linters
        run: make linter
